{
 "title": "Network Device Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(intf_stats_carrier_transitions,source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC Server Access Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "grpc_stats_access_rejected{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Server Access Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "grpc_stats_access_accepted{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Interface Input bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "intf_stats_in_bps{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Output bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "intf_stats_out_bps{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Input Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "intf_stats_in_error_packets{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "intf_stats_out_error_packets{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Input Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "intf_stats_in_discarded_packets{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Output Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "intf_stats_out_discarded_packets{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Flaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "intf_stats_carrier_transitions{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total BGP Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bgp_stats_total_peers{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BGP Down Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "bgp_stats_total_peers{source=~\"$device\"} - bgp_stats_up_peers{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "cpu_instant{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "memory_utilization{source=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}