global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
    - to: @gmail.com
      from: @gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: @gmail.com
      auth_password: [password]
      send_resolved: true